source 'https://rubygems.org'

gem 'sinatra'
gem "sinatra-cross_origin", "~> 0.3.1"
gem 'sinatra-jsonp'
gem 'sinatra-contrib', require: false
gem 'sinatra-mapping'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'shotgun'
gem 'byebug'
gem 'slim'
gem 'puma'
gem 'coffee-script'
gem 'activerecord'
gem 'faker'
gem 'dotenv'
gem 'rake'
gem 'sqlite3'

group :development do
  gem 'pry'
  gem 'tux'
end
