require './app'
require 'dotenv/tasks'
require 'dotenv'
Dotenv.load

task :default do
  set :database, {adapter: "sqlite3", database: ENV['DATABASE_URL']}
  set :database_file, "#{APP_ROOT}/db/colorhiro.sqlite3"
end

require 'sinatra/activerecord/rake'
require 'sinatra/activerecord'
# require 'rspec/core/rake_task'

# RSpec::Core::RakeTask.new(:spec)
#
# task :default => :spec
# task :release do
# 	`rake build`
# 	# `gem inabox`
# 	exit
# end
#
# require "bundler/gem_tasks"
